Document: iquest
Title: Debian iquest Manual
Author: <insert document author here>
Abstract: This manual describes what iquest is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/iquest/iquest.sgml.gz

Format: postscript
Files: /usr/share/doc/iquest/iquest.ps.gz

Format: text
Files: /usr/share/doc/iquest/iquest.text.gz

Format: HTML
Index: /usr/share/doc/iquest/html/index.html
Files: /usr/share/doc/iquest/html/*.html
