#!/usr/bin/env php
<?php

if (!isset($_SERVER['SERVER_NAME'])) $_SERVER['SERVER_NAME']='';

$_required_modules = array('iquest', 'iquest-cli', 'auth', 'console');

require_once(dirname(__FILE__)."/../config/set_env.php");
require_once(dirname(__FILE__)."/../functions/functions.php");
require_once(getenv('SERWEB_DIR')."functions/bootstrap.php");

function usage(){

    echo "Add new traccar device or update existing for every team in DB table having tracker_id configured.\n\n";
    echo "Usage: ".$_SERVER['argv'][0]." [-h] \n\n";

}

function get_traccar_group($traccar){

    $traccar_group_name = Iquest_Options::get(Iquest_Options::TRACCAR_GROUP);
    if (!$traccar_group_name) return null;

    $traccar_group = $traccar->get_group_by_name($traccar_group_name);
    if (!$traccar_group){
        throw new Iquest_InvalidConfigException("Traccar group '$traccar_group_name' does not exists on the server.");
    }

    return $traccar_group;
}


function traccar_update(){
    $traccar = new Traccar([
        'auth_token' => Iquest_Options::get(Iquest_Options::TRACCAR_AUTH_TOKEN),
        'server_addr' => Iquest_Options::get(Iquest_Options::TRACCAR_ADDR)
    ]);

    $teams = Iquest_Team::fetch();
    $traccar_group = get_traccar_group($traccar);

    $device_updated = false;
    foreach($teams as $team){
        if (!$team->tracker_id) continue;

        $device = $traccar->get_device($team->tracker_id);

        $insert = false;
        if (!$device){
            $insert = true;
            $device = new Traccar_device();
            $device->uniqueId = $team->tracker_id;
        }

        $device->name = $team->name;
        if ($traccar_group) $device->groupId = $traccar_group->id;

        if ($insert) {
            Console::log("Inserting device for team: {$team->name}", Console::CYAN);
            $traccar->insert_device($device);
        }
        else{
            Console::log("Updating device for team: {$team->name}", Console::CYAN);
            $traccar->update_device($device);
        }

        $device_updated = true;
    }

    if (!$device_updated){
        Console::log("There is no team with tracker configured in DB table.", Console::RED);
    }
}

function main(){

    if ($_SERVER['argc'] > 1){
        usage();
        exit;
    }

    try{
        traccar_update();
    }
    catch (Iquest_InvalidConfigException $e){
        fwrite(STDERR, "\nSORRY VOLE ERROR:\n");
        Console_Cli::print_exception_error($e);
        exit(1);
    }
    catch(Traccar_api_query_exception $e){
        fwrite(STDERR, "\nSORRY VOLE ERROR:\n");
        Console_Cli::print_exception_error($e);
        exit(1);
    }
    catch (exception $e){
        fwrite(STDERR, "\nUnexpected exception. See PHP error log for details:\n");
        Console_Cli::print_exception_error($e);
        throw $e;
    }

}


main();
